# Uncomment the next line to define a global platform for your project
platform :ios, '15.4'

target 'LibTorchWrapper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LibTorchWrapper
  pod 'LibFatTorch-Lite', :git => 'https://github.com/Timeworx/pytorch-lite-ios.git'
  
end
